### ISSUE TITLE
Yocto failed to fetch tag 2.1.5

### ISSUE THREAD

**Issue by michaelchao** [GENIVI/capicxx-core-runtime#12]
In my yocto environment(bitbake version is 1.24.0)
I found yocto failed to download the specified tag 2.1.5 of capicxx-core-runtime 
my bb file's content is like blow:

> SRCREV = "210ce21e5763e7dcb164803e3d21b8302f87e2e9" // this commit id is tag 2.1.5

> SRC_URI = "git://github.com/GENIVI/capicxx-core-runtime.git; "

After this error, I tracked bitbake execution route, and found these commands:
1. git -c core.fsyncobjectfiles=0 clone --bare --mirror git://github.com/GENIVI/capicxx-core-runtime.git github.com.GENIVI.capicxx-core-runtime.git 
2. cd the directory github.com.GENIVI.capicxx-core-runtime.git generated by the first step
3. git -c core.fsyncobjectfiles=0 branch --contains 210ce21e5763e7dcb164803e3d21b8302f87e2e9 --list master 2> /dev/null | wc -l
 
output "0"

For validating result，I did a test on an github project poco
1. git -c core.fsyncobjectfiles=0 clone --bare --mirror git://github.com/pocoproject/poco.git github.com.pocoproject.poco.git
2. cd directory github.com.pocoproject.poco.git
3. git -c core.fsyncobjectfiles=0 branch --contains bfbe6a328744eaa84cb443b93ee20947aa0be91f --list master 2> /dev/null | wc -l

the commit id belongs to poco's tag 1.7.9
output "1"

I wonder, why capicxx-core-runtime doesn't work with above steps?

**Comment by gunnarx** [comment]
Sometimes these things are just a temporary fetching error...  

But to check, let's start with which version of meta-ivi you are trying to build. Please report the commit hash of meta-ivi, so that we are looking at the same thing.

**Comment by gunnarx** [comment]
Or do you have your own custom .bb file?  If so, it might help if you post it.  Building in yocto is not sure to be the right support channel here in the capicxx component project, but we could take a quick look.

**Comment by gunnarx** [comment]
@michaelchao Commit hash 210ce21e5763e7dcb164803e3d21b8302f87e2e9 and tag 2.1.5 is over 5 years old...

I would say that no one is likely provide any support on such old versions.

I do agree with you, it looks like that commit does not seem to be on the master branch, and I can imagine there was a reorganization done back at that time because I found a few other references to 2.1.5 on the master branch.  

What you have already found is that bitbake only fetches part of the tree (in this case only what is referred by master branch) and then it might not get the commit you need. 

Referring to : https://www.yoctoproject.org/docs/latest/mega-manual/mega-manual.html#git-fetcher

I would say that adding either ";nobranch=1" or ";tag=2.1.5" on to the SRC_URI seems like it might make your recipe work.    But I **really** don't recommend using such an old version.  It's very likely to have bugs that have been fixed later on.

Can we close the issue @michaelchao?

**Comment by michaelchao** [comment]
OK, thank you for your answer

**Comment by michaelchao** [comment]
Sorry to reopen this question, 
First , with "nobranch=1", I can fetch 2.1.5 successfully, thank you:)
I have one last thing for capicxx-core-runtime
In this project, there is a patch file for 2.1.5

> --- git/configure.ac	2016-09-05 09:47:15.875109831 +0800
> +++ git/configure.ac-new	2016-09-05 09:58:41.727130151 +0800
> @@ -4,9 +4,9 @@
>          [],
>          [CommonAPI])
> +AC_CONFIG_AUX_DIR([build-aux])
> AC_CONFIG_MACRO_DIR([m4])
> m4_ifdef([AM_PROG_AR], [AM_PROG_AR])
> -AC_CONFIG_AUX_DIR([build-aux])
> AC_CONFIG_HEADERS([build-aux/config.h])
> AC_CONFIG_FILES([
>  		Makefile

And, is this patch still suitable for 2.1.5?

**Comment by gunnarx** [comment]
>  In this project, there is a patch file for 2.1.5

In what project?

> And, is this patch still suitable for 2.1.5?

I don't think anyone can answer that...  First, because as I said we would recommend you to instead upgrade to a newer version.  And secondly, if you have a kind of "private" project, then any patches that are added there are your own responsibility to keep up to date.  If you were asking about for example meta-ivi, where we maintain Yocto build recipes for these components, then it would be different (but we still don't provide support for several years old versions).

You could just try the patch and find out yourself.

**Comment by michaelchao** [comment]
Our company‘s yocto project. For now, I have a very simple question.
In 2.1.5, this tag, is there any strings like one of that path content ?
For example, is there "AC_CONFIG_AUX_DIR" in any file of 2.1.5?

**Comment by michaelchao** [comment]
I found a CommAPI.path file in 2.1.5, and its content is same as my project. So problem seems to be resolved. Thank you for your help
